### ISSUE TITLE
[Request] GroupBy

### ISSUE THREAD

**Issue by bastienJS** [schmuli/linq.es6#1]
Is it possible that you implement a GroupBy function?

I want to advance from javascript to typescript with my project and still look for all linq.js pendants ;-)

**Comment by schmuli** [comment]
First, thanks for your interest, and yes, I will try to implement GroupBy (and other) functionality soon.

However, please be aware that this code is written using ES6 and not TypeScript, and uses Iterators which are expected in TypeScript 1.5 and Generators which are expected in TypeScript 1.6, both of which are not yet released. Please see the [TypeScript Roadmap](https://github.com/Microsoft/TypeScript/wiki/Roadmap).

Additionally, browser (and Node) support for these features are not yet widespread and may require Beta versions or feature flags to work. This project was an experiment to try to use these brand new features to implement a lazy evaluated version of LINQ in JavaScript.
